### ISSUE TITLE
Arrays

### ISSUE THREAD

**Issue by mariobrosch** [queenvictoria/ember-cli-openapi-generate#7]
Hi,

Arrays are not possible in Ember by default as a type in the model. I read this post:
https://stackoverflow.com/questions/12168570/how-to-represent-arrays-within-ember-data-models

Is it possible to generate the transform during installation of this addon? Since it is common to use string-arrays of int-arrays on objects. For instance when we look at the petstore example the field Pet:PhotoUrls is a string array. 

Is that possible to add?

**Comment by queenvictoria** [comment]
Could you show me the bit of the swagger/openapi you are using? And the expected output in the model? Is this the same as pull request #8 ?

**Comment by mariobrosch** [comment]
long time ago, dont know if its the same. 

im using the petstore examples

**Comment by queenvictoria** [comment]
Sorry what are petstore examples? I'm working through your PR in #8. If that supersedes this issue feel free to close it.

**Comment by mariobrosch** [comment]
if you google for a swagger example, you'll get the petstore examples as one of the first hits.

in the mean time we have stopped with this plugin and created our own (in-repo addon)
